### ISSUE TITLE
Adobe Launch Audit API

### ISSUE THREAD

**Issue by alcazes** [adobe/reactor-developer-docs#92]
We are trying to figure out who deleted one of our web property.

Does the adobe launch audit API allows to see who created or deleted a web property ?

**Comment by thebenrob** [comment]
The system records the audit events, but we are just today made aware of a bug that prevents audit events from deleted properties from being returned by the API - we think because that property is no longer included in a group that the user has permissions to (which it can't because it no longer exists).

So we do have information for property deletes, but it is not currently exposed in a way that you can get to it on your own.  If you want to contact me by email/Slack with and I can help you get some info.
